# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'Windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.0'
  inputs:
    packageType: sdk
    version: 3.0.100

- task: DotNetCoreCLI@2
  displayName: Publish single-exe x64
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src\Frickler\Frickler.csproj'
    arguments: '-f netcoreapp3.0 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true /p:RuntimeIdentifier=win-x64'
    zipAfterPublish: false

- task: CmdLine@2
  displayName: Rename single-exe x64
  inputs:
    script: 'rename $(Build.SourcesDirectory)\src\Frickler\bin\Release\netcoreapp3.0\win-x64\publish\Frickler.exe Frickler-x64.exe'

- task: DotNetCoreCLI@2
  displayName: Publish single-exe x86
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src\Frickler\Frickler.csproj'
    arguments: '-f netcoreapp3.0 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true /p:RuntimeIdentifier=win-x86'
    zipAfterPublish: false

- task: CmdLine@2
  displayName: Rename single-exe x86
  inputs:
    script: 'rename $(Build.SourcesDirectory)\src\Frickler\bin\Release\netcoreapp3.0\win-x86\publish\Frickler.exe Frickler-x86.exe' 

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src\Frickler\bin\Release\netcoreapp3.0'
    Contents: |
     win-x64\publish\Frickler-x64.exe
     win-x86\publish\Frickler-x86.exe
    TargetFolder: '$(build.artifactstagingdirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
